[package]
name = "search-server"
version = "0.1.0"
edition = "2024"

[dependencies]
bookit-telemetry = { version = "0.1.0", path = "../../packages/telemetry" }
bookit-db = { path = "../../packages/db" }
diesel = { version = "2.2.0", features = ["postgres", "r2d2", "chrono"] }
bookit-proto = { path = "../../packages/proto" }
prost = "0.13"
tonic = "0.12"
axum = { version = "0.7.5", features = ["ws", "multipart"] }
tokio = { version = "1.37.0", features = ["full", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.5.2", features = ["cors"] }
reqwest = { version = "0.12", features = ["json"] }
mongodb = { version = "3" }
bson = { version = "2", features = ["chrono-0_4"] }
bookit-mongo = { path = "../../packages/mongo-conn" }
redis-conn = { path = "../../packages/redis-conn" }
redis = { version = "1.4.1", features = ["tokio-native-tls-comp", "tokio-comp", "json"] }
dotenvy = "0.15.7"
futures = "0.3.32"
chrono = { version = "0.4", features = ["serde"] }
