ALTER TABLE movies ADD COLUMN tagline VARCHAR;
ALTER TABLE movies ADD COLUMN genre TEXT[];
ALTER TABLE movies ADD COLUMN score REAL;
ALTER TABLE movies ADD COLUMN director VARCHAR;
ALTER TABLE movies ADD COLUMN cast_names TEXT[];
ALTER TABLE movies ADD COLUMN language VARCHAR;
ALTER TABLE movies ADD COLUMN backdrop_url VARCHAR;
ALTER TABLE movies ADD COLUMN status VARCHAR;
